docker run -it -d  \
  --label traefik.http.routers.essam.rule=Host\(\`essam.phamasoft.com\`\) \
  --label traefik.http.routers.essam.tls.certresolver=lets-encrypt \
  --label traefik.http.routers.essam.tls=true \
  --label traefik.http.routers.essam.service=essam-http \
  --label traefik.http.services.essam-http.loadbalancer.server.port=80 \
  --name essam \
  --network web \
  --restart always \
  --expose 80 \
  mikoposoft/hekimavipodozi
